"""Generic SEC HTML financial statement builder (6-K / 20-F foreign issuers)."""

from __future__ import annotations

import html
import re
import time
import urllib.request
from dataclasses import dataclass
from typing import Any, Literal

from bs_xbrl import verify_bs_rows
from cf_xbrl import verify_cf_rows
from income_xbrl import (
    fiscal_quarter_label,
    fiscal_year_end_month,
    load_entity,
    quarter_label,
    to_num,
    verify_income_rows,
)
from number_format import fmt_dollar, fmt_eps, fmt_margin, fmt_pct_yoy as fmt_pct
from sec_financials import (
    FPI_QUARTERLY_FORMS,
    is_fpi_quarterly_doc,
    json_path,
    latest_quarterly_filings,
    lookup_cik,
    save_json,
    sec_get,
    sec_user_agent,
)
from statement_templates import (
    BALANCE_SHEET_ROWS,
    CASH_FLOW_ROWS,
    INCOME_ROWS,
    row_from_spec,
    section_divider_row,
)

StatementKind = Literal["income", "balance-sheet", "cash-flow"]
PeriodKey = tuple[int, int]  # (calendar_year, quarter 1-4)

MONTHS = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}

INCOME_ALIASES: dict[str, str] = {
    "total net sales": "rev",
    "net sales": "rev",
    "net revenue": "rev",
    "revenue": "rev",
    "cost of goods sold": "cogs",
    "cost of sales": "cogs",
    "total cost of sales": "cogs",
    "gross profit": "gross",
    "gross margin": "gm_pct",
    "gross margin (%)": "gm_pct",
    "operating profit": "op",
    "operating profit (ebit)": "op",
    "income from operations": "op",
    "operating income": "op",
    "profit before income taxes": "pretax",
    "income before provision for income taxes": "pretax",
    "income taxes": "tax",
    "provision for income taxes": "tax",
    "net income": "net",
    "net profit": "net",
    "profit for the period": "net",
    "net profit for the period": "net",
    "income after income taxes": "net_after_tax",
    "net profit": "net",
    "profit for the period": "net",
    "total revenues": "rev",
    "total revenue": "rev",
    "sales": "rev",
    "end-quarter cash and cash equivalents and short-term investments": "cash",
    "cash and cash equivalents at end of the period": "cash_end",
    "cash and cash equivalents at end of period": "cash_end",
}

BS_ALIASES: dict[str, str] = {
    "cash and cash equivalents": "cash",
    "total assets": "assets",
    "total current assets": "current_assets",
    "total noncurrent assets": "noncurrent_assets",
    "total liabilities": "liab",
    "total equity": "equity",
    "total shareholders' equity": "equity",
    "total shareholders equity": "equity",
    "shareholders' equity": "equity",
    "equity attributable to shareholders of the parent": "equity",
    "total equity and liabilities": "skip",
}

CF_ALIASES: dict[str, str] = {
    "net cash flows from operating activities": "op_cf",
    "cash flows from operating activities": "op_cf",
    "cash generated from operating activities": "op_cf",
    "net cash generated by operating activities": "op_cf",
    "net cash used in operating activities": "op_cf",
    "net cash flows from investing activities": "inv_cf",
    "cash flows from investing activities": "inv_cf",
    "net cash used in investing activities": "inv_cf",
    "net cash generated by investing activities": "inv_cf",
    "net cash flows from financing activities": "fin_cf",
    "cash flows from financing activities": "fin_cf",
    "net cash used in financing activities": "fin_cf",
    "net cash generated by financing activities": "fin_cf",
    "net change in cash and cash equivalents": "net_chg",
    "net increase in cash and cash equivalents": "net_chg",
    "net increase/(decrease) in cash and cash equivalents": "net_chg",
    "capital expenditure": "capex",
    "payments for property, plant and equipment": "capex",
    "purchase of property, plant and equipment": "capex",
    "acquisitions of property, plant and equipment": "capex",
}


@dataclass
class ColumnSpec:
    idx: int
    kind: Literal["quarter", "instant"]
    year: int
    quarter: int
    period_end: str
    label: str
    ytd_months: int = 3


@dataclass
class ParsedTable:
    rows: list[list[str]]
    columns: list[ColumnSpec]
    scale: float = 1.0
    currency: str = "USD"


def sec_get_html(url: str) -> str:
    last_err: Exception | None = None
    for attempt in range(3):
        try:
            time.sleep(0.11)
            req = urllib.request.Request(url, headers={"User-Agent": sec_user_agent()})
            with urllib.request.urlopen(req, timeout=120) as resp:
                return resp.read().decode("utf-8", errors="replace")
        except OSError as e:
            last_err = e
            time.sleep(2.0 * (attempt + 1))
    raise last_err  # type: ignore[misc]


def filing_index(cik: str, accession: str) -> dict[str, Any]:
    acc = accession.replace("-", "")
    return sec_get(f"https://www.sec.gov/Archives/edgar/data/{int(cik)}/{acc}/index.json")


def filing_doc_url(cik: str, accession: str, doc: str) -> str:
    acc = accession.replace("-", "")
    return f"https://www.sec.gov/Archives/edgar/data/{int(cik)}/{acc}/{doc}"


def clean_cell(text: str) -> str:
    text = html.unescape(re.sub(r"<[^>]+>", " ", text))
    return " ".join(text.split())


def parse_number(raw: str) -> float | None:
    if not raw or raw.strip() in ("—", "-", "", "N/A", "n/a"):
        return None
    neg = raw.strip().startswith("(") and raw.strip().endswith(")")
    s = raw.replace(",", "").replace("$", "").replace("€", "").replace("%", "").strip("()").strip()
    if not s or s in ("—", "-"):
        return None
    try:
        v = float(s)
    except ValueError:
        return None
    return -v if neg else v


def normalize_label(label: str) -> str:
    return re.sub(r"\s+", " ", label.strip().lower()).rstrip(":")


def parse_q_header(label: str) -> tuple[int, int] | None:
    m = re.match(r"Q([1-4])\s+(\d{4})", label.strip(), re.I)
    if not m:
        return None
    return int(m.group(2)), int(m.group(1))


def parse_date_header(label: str) -> str | None:
    label = label.strip()
    m = re.match(r"(\d{1,2})\s+([A-Za-z]{3})\s+(\d{4})", label)
    if m:
        day, mon = int(m.group(1)), MONTHS.get(m.group(2).lower()[:3])
        if mon:
            return f"{int(m.group(3)):04d}-{mon:02d}-{day:02d}"
    m = re.match(r"([A-Za-z]{3,9})\s+(\d{1,2}),?\s+(\d{4})", label, re.I)
    if m:
        mon = MONTHS.get(m.group(1).lower()[:3])
        if mon:
            day = int(m.group(2))
            return f"{int(m.group(3)):04d}-{mon:02d}-{day:02d}"
    return None


def period_end_for_quarter(year: int, quarter: int) -> str:
    month_day = {1: (3, 31), 2: (6, 30), 3: (9, 30), 4: (12, 31)}
    m, d = month_day[quarter]
    return f"{year:04d}-{m:02d}-{d:02d}"


def date_to_period_key(period_end: str, fy_end_month: int) -> PeriodKey:
    y, m, _ = map(int, period_end.split("-"))
    fy = y if m <= fy_end_month else y + 1
    start_month = (fy_end_month % 12) + 1
    elapsed = (m - start_month) if m >= start_month else (12 - start_month) + m
    q = elapsed // 3 + 1
    return fy, q


FPI_FINANCIAL_DOC_RE = re.compile(
    r"(fsx|financial|consolidated|standalone|caq|earnings|quarter)",
    re.I,
)


def list_html_filings(cik: str, limit: int = 25) -> list[dict[str, str]]:
    """Quarterly 6-K filings with financial HTML (fsx / consolidated exhibits)."""
    sub = sec_get(f"https://data.sec.gov/submissions/CIK{int(cik):010d}.json")
    recent = sub["filings"]["recent"]
    by_report: dict[str, tuple[int, dict[str, str]]] = {}
    for i, form in enumerate(recent["form"]):
        if form not in FPI_QUARTERLY_FORMS:
            continue
        pe = recent.get("reportDate", [""])[i] or ""
        if not pe:
            continue
        doc = recent.get("primaryDocument", [""])[i] or ""
        score = 0
        if FPI_FINANCIAL_DOC_RE.search(doc):
            score += 100
        if "fsx" in doc.lower():
            score += 50
        entry = {
            "form": form,
            "filingDate": recent["filingDate"][i],
            "accessionNumber": recent["accessionNumber"][i],
            "reportDate": pe,
            "primaryDocument": doc,
            "url": filing_doc_url(cik, recent["accessionNumber"][i], doc),
        }
        prev = by_report.get(pe)
        if prev is None or score > prev[0]:
            by_report[pe] = (score, entry)
    ranked = sorted(by_report.values(), key=lambda x: x[1]["reportDate"], reverse=True)
    out = [entry for score, entry in ranked if score > 0][:limit]
    if len(out) < limit:
        seen = {f["reportDate"] for f in out}
        for score, entry in ranked:
            if entry["reportDate"] in seen:
                continue
            out.append(entry)
            seen.add(entry["reportDate"])
            if len(out) >= limit:
                break
    return out


def _htm_candidates(index: dict[str, Any], primary: str) -> list[tuple[str, int]]:
    """Rank .htm exhibits by size (larger → more likely full financial report)."""
    ranked: list[tuple[str, int]] = []
    for item in index.get("directory", {}).get("item", []):
        name = item.get("name", "")
        if not name.lower().endswith(".htm"):
            continue
        try:
            size = int(str(item.get("size", "0") or "0"))
        except ValueError:
            size = 0
        ranked.append((name, size))
    ranked.sort(key=lambda x: -x[1])
    return ranked


def locate_financial_docs(index: dict[str, Any], primary: str, min_size: int = 20_000) -> list[str]:
    """Content-neutral: prefer large HTML exhibits (financial reports, not cover pages)."""
    ranked = _htm_candidates(index, primary)
    out: list[str] = []
    for name, size in ranked:
        if size >= min_size or (size == 10**9):
            out.append(name)
    if not out and ranked:
        out.append(ranked[0][0])
    return out


def html_has_financial_tables(html_text: str) -> bool:
    """Quick content check before full parse."""
    low = html_text.lower()
    markers = ("net sales", "net revenue", "total assets", "operating activities", "gross profit")
    return sum(1 for m in markers if m in low) >= 2


def extract_tables(html_text: str) -> list[list[list[str]]]:
    tables: list[list[list[str]]] = []
    for block in re.findall(r"<table[^>]*>(.*?)</table>", html_text, re.I | re.S):
        rows: list[list[str]] = []
        for tr in re.findall(r"<tr[^>]*>(.*?)</tr>", block, re.I | re.S):
            cells = [clean_cell(c) for c in re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", tr, re.I | re.S)]
            if cells:
                rows.append(cells)
        if rows:
            tables.append(rows)
    return tables


def detect_scale_and_currency(rows: list[list[str]]) -> tuple[float, str]:
    text = " ".join(" ".join(r) for r in rows[:8]).lower()
    currency = "USD"
    for code in ("eur", "dkk", "gbp", "chf", "jpy", "twd", "nt$", "ntd", "new taiwan"):
        if code in text:
            currency = code.upper().replace("NT$", "TWD").replace("NTD", "TWD").replace("NEW TAIWAN", "TWD")
            break
    if "million" in text or " mn" in text:
        return 1.0, currency
    if "thousand" in text:
        return 0.001, currency
    # Infer from magnitude in first numeric data cells
    for row in rows[3:15]:
        for cell in row[1:]:
            v = parse_number(cell)
            if v is not None and abs(v) > 1e8:
                return 1e-6, currency
    return 1.0, currency


def align_amount_column_indices(header_rows: list[list[str]], header_indices: list[int]) -> list[int]:
    """Map date/year header columns to Amount sub-columns (TSM %/Amount pairs)."""
    amount_cols: list[int] = []
    for row in header_rows:
        amount_cols = [i for i, c in enumerate(row) if normalize_label(c) == "amount"]
        if amount_cols:
            break
    if not amount_cols:
        return header_indices
    n = len(header_indices)
    # 3M + 6M layouts interleave Amount columns: use every other Amount for quarterly pairs.
    if n * 2 <= len(amount_cols):
        return [amount_cols[i * 2] if i * 2 < len(amount_cols) else amount_cols[-1] for i in range(n)]
    out: list[int] = []
    for hi in header_indices:
        candidates = [a for a in amount_cols if a >= hi]
        out.append(candidates[0] if candidates else hi)
    return out


def ytd_block_start(header_rows: list[list[str]]) -> int:
    """Column index where 6M/9M/12M YTD blocks begin (exclude from quarterly parse)."""
    start = 10_000
    for row in header_rows:
        for i, cell in enumerate(row):
            low = cell.lower()
            if any(
                p in low
                for p in (
                    "six months ended",
                    "nine months ended",
                    "twelve months ended",
                    "year ended",
                    "years ended",
                )
            ):
                start = min(start, i)
    return start


def dedupe_columns(cols: list[ColumnSpec]) -> list[ColumnSpec]:
    seen: set[str] = set()
    out: list[ColumnSpec] = []
    for c in cols:
        if c.period_end in seen:
            continue
        seen.add(c.period_end)
        out.append(c)
    return out


YTD_MONTH_MAP = {"three": 3, "six": 6, "nine": 9, "twelve": 12}


def parse_period_ended_columns(header_rows: list[list[str]], fy_end_month: int) -> list[ColumnSpec]:
    """Three/Six/Nine Months Ended … / year / Amount sparse layouts."""
    month, day, ytd_months = 12, 31, 3
    for header in header_rows:
        text = " ".join(header).lower()
        m = re.search(
            r"(three|six|nine|twelve)\s+months?\s+ended\s+(\d{1,2})?\s*([a-z]{3,9})\s*(\d{1,2})?",
            text,
            re.I,
        )
        if m:
            ytd_months = YTD_MONTH_MAP.get(m.group(1).lower(), 3)
            mon_name = m.group(3).lower()[:3]
            mon = MONTHS.get(mon_name)
            if mon:
                month = mon
                day = int(m.group(2)) if m.group(2) else (30 if mon in (4, 6, 9, 11) else 31)
    year_cells: list[tuple[int, int]] = []
    for header in header_rows:
        for i, cell in enumerate(header):
            if cell and re.match(r"^\d{4}$", cell.strip()):
                year_cells.append((i, int(cell.strip())))
    if not year_cells:
        return []
    years_only = [y for _, y in year_cells]
    if len(years_only) >= 4 and len(years_only) % 2 == 0:
        half = len(years_only) // 2
        if years_only[:half] == years_only[half:]:
            year_cells = year_cells[:half]
    amount_idxs = align_amount_column_indices(header_rows, [i for i, _ in year_cells])
    cols: list[ColumnSpec] = []
    for (hi, year), ai in zip(year_cells, amount_idxs):
        pe = f"{year:04d}-{month:02d}-{day:02d}"
        pk = date_to_period_key(pe, fy_end_month)
        cols.append(
            ColumnSpec(
                idx=ai,
                kind="quarter",
                year=pk[0],
                quarter=pk[1],
                period_end=pe,
                label=str(year),
                ytd_months=ytd_months,
            )
        )
    return dedupe_columns(cols)


def parse_columns(header_rows: list[list[str]], column_mode: Literal["quarter", "instant"], fy_end_month: int) -> list[ColumnSpec]:
    cols = parse_q_columns(header_rows) if column_mode == "quarter" else parse_instant_columns(header_rows, fy_end_month)
    if cols:
        return dedupe_columns(cols)
    if column_mode == "quarter":
        return parse_period_ended_columns(header_rows, fy_end_month)
    return []


def parse_q_columns(header_rows: list[list[str]]) -> list[ColumnSpec]:
    for header in header_rows:
        cols: list[ColumnSpec] = []
        for i, cell in enumerate(header):
            if not cell:
                continue
            q = parse_q_header(cell)
            if q:
                year, quarter = q
                pe = period_end_for_quarter(year, quarter)
                cols.append(
                    ColumnSpec(
                        idx=i,
                        kind="quarter",
                        year=year,
                        quarter=quarter,
                        period_end=pe,
                        label=cell,
                    )
                )
        if cols:
            return cols
    return []


def parse_instant_columns(header_rows: list[list[str]], fy_end_month: int) -> list[ColumnSpec]:
    date_cells: list[tuple[int, str]] = []
    for header in header_rows:
        for i, cell in enumerate(header):
            if not cell:
                continue
            pe = parse_date_header(cell)
            if pe:
                date_cells.append((i, pe))
    if not date_cells:
        return []
    amount_idxs = align_amount_column_indices(header_rows, [i for i, _ in date_cells])
    cols: list[ColumnSpec] = []
    for (hi, pe), ai in zip(date_cells, amount_idxs):
        year, quarter = date_to_period_key(pe, fy_end_month)
        cols.append(
            ColumnSpec(
                idx=ai,
                kind="instant",
                year=year,
                quarter=quarter,
                period_end=pe,
                label=pe,
            )
        )
    return dedupe_columns(cols)


def table_labels(rows: list[list[str]]) -> list[str]:
    return [normalize_label(r[0]) for r in rows if r and r[0]]


def table_score(rows: list[list[str]], needles: tuple[str, ...]) -> int:
    labels = table_labels(rows)
    text = " ".join(labels)
    return sum(10 for n in needles if n in text)


def _header_text(header_rows: list[list[str]]) -> str:
    return " ".join(" ".join(r) for r in header_rows[:8]).lower()


def quarterly_table_adjustment(header_rows: list[list[str]], cols: list[ColumnSpec]) -> int:
    """Prefer Q1–Q4 / three-month tables over full-year year-vs-year P&L layouts."""
    text = _header_text(header_rows)
    bonus = 0
    if re.search(r"\bq[1-4]\b", text):
        bonus += 50
    if "three months ended" in text:
        bonus += 40
    if any(parse_q_header(c.label) for c in cols):
        bonus += 50
    year_only = [c.label.strip() for c in cols if re.fullmatch(r"\d{4}", c.label.strip())]
    if len(year_only) >= 2 and bonus == 0:
        bonus -= 45
    if any(p in text for p in ("year ended", "years ended", "twelve months ended")) and bonus == 0:
        bonus -= 35
    if re.search(r"profit and loss\s+\d{4}\s+\d{4}", text) and bonus == 0:
        bonus -= 40
    return bonus


def find_best_table(
    tables: list[list[list[str]]],
    needles: tuple[str, ...],
    column_mode: Literal["quarter", "instant"],
    fy_end_month: int,
) -> ParsedTable | None:
    best: ParsedTable | None = None
    best_score = 0
    for rows in tables:
        score = table_score(rows, needles)
        if score <= 0:
            continue
        header_rows = rows[:12]
        cols = parse_columns(header_rows, column_mode, fy_end_month)
        if not cols:
            continue
        score += len(cols)
        if column_mode == "quarter":
            score += quarterly_table_adjustment(header_rows, cols)
        if score > best_score:
            scale, currency = detect_scale_and_currency(rows)
            best = ParsedTable(rows=rows, columns=cols, scale=scale, currency=currency)
            best_score = score
    return best


def alias_key(label: str, aliases: dict[str, str]) -> str | None:
    nl = normalize_label(label)
    if nl in aliases:
        return aliases[nl]
    if "eps (basic" in nl:
        return "eps_b"
    for prefix, key in aliases.items():
        if nl == prefix or nl.startswith(prefix + " "):
            return key
    return None


def extract_metrics(table: ParsedTable, aliases: dict[str, str]) -> dict[str, list[float | None]]:
    out: dict[str, list[float | None]] = {}
    col_count = len(table.columns)

    def cell_value(row: list[str], idx: int) -> float | None:
        for off in (0, 1):
            j = idx + off
            if j >= len(row):
                break
            num = parse_number(row[j])
            if num is not None:
                return round(num * table.scale, 2)
        return None

    for row in table.rows:
        if not row or not row[0]:
            continue
        nl = normalize_label(row[0])
        if nl.startswith("...") or nl.startswith("("):
            continue
        key = alias_key(row[0], aliases)
        if not key or key == "skip":
            continue
        vals: list[float | None] = []
        for col in table.columns:
            vals.append(cell_value(row, col.idx))
        if len(vals) == col_count:
            if key in out:
                if sum(v is not None for v in vals) <= sum(v is not None for v in out[key]):
                    continue
            out[key] = vals
    return out


def period_keys_from_table(table: ParsedTable) -> list[tuple[PeriodKey, ColumnSpec]]:
    return [((col.year, col.quarter), col) for col in table.columns]


def merge_metric(
    store: dict[PeriodKey, dict[str, Any]],
    key: PeriodKey,
    field: str,
    value: float | None,
    source: dict[str, str],
) -> None:
    if value is None:
        return
    entry = store.setdefault(key, {"source": source, "fields": {}})
    if entry["fields"].get(field) is None:
        entry["fields"][field] = value


SLIDE_INCOME_LABELS: tuple[str, ...] = (
    "total net sales",
    "total cost of sales",
    "gross profit",
    "research and development costs",
    "selling, general and administrative costs",
    "income from operations",
    "interest and other, net",
    "income before income taxes",
    "income tax expense",
    "benefit from (provision for) income taxes",
    "income after income taxes",
    "net income",
    "basic net income per ordinary share",
)

SLIDE_INCOME_FORCE_FIELDS = frozenset({"rev", "cogs", "gross", "op", "pretax", "tax", "net", "eps_b"})


def extract_hidden_slide_blocks(html_text: str) -> list[str]:
    """OCR-style text embedded in image-slide exhibits (e.g. ASML financialstatementsusgaa.htm)."""
    blocks = re.findall(r'<FONT[^>]*color:\s*white[^>]*>(.*?)</FONT>', html_text, re.I | re.S)
    out: list[str] = []
    for block in blocks:
        clean = html.unescape(re.sub(r"\s+", " ", block).strip())
        if len(clean) > 200:
            out.append(clean)
    return out


def parse_slide_period_ends(text: str) -> list[str]:
    m = re.search(r"three months ended(.+?)(?:\(unaudited|20\d{2})", text, re.I)
    if not m:
        return []
    chunk = m.group(1)
    dates = re.findall(r"([A-Za-z]{3,9})\s+(\d{1,2})", chunk)
    years = re.findall(r"\b(20\d{2})\b", text[m.start() : m.start() + 500])
    if not dates or not years:
        return []
    n = min(len(dates), len(years))
    out: list[str] = []
    for i in range(n):
        mon = MONTHS.get(dates[i][0].lower()[:3])
        day = int(dates[i][1])
        year = int(years[i])
        if mon:
            out.append(f"{year:04d}-{mon:02d}-{day:02d}")
    return out


def _slide_label_key(label: str) -> str | None:
    key = alias_key(label, INCOME_ALIASES)
    if key:
        return key
    if label == "income from operations":
        return "op"
    if label == "total cost of sales":
        return "cogs"
    if label == "income after income taxes":
        return "net_after_tax"
    if label == "basic net income per ordinary share":
        return "eps_b"
    return None


def parse_slide_income_block(text: str, fy_end_month: int) -> ParsedTable | None:
    low = text.lower()
    if "total net sales" not in low or "income from operations" not in low:
        return None
    period_ends = parse_slide_period_ends(text)
    if not period_ends:
        return None
    n = len(period_ends)
    cols: list[ColumnSpec] = []
    for i, pe in enumerate(period_ends):
        pk = date_to_period_key(pe, fy_end_month)
        cols.append(
            ColumnSpec(
                idx=i + 1,
                kind="quarter",
                year=pk[0],
                quarter=pk[1],
                period_end=pe,
                label=pe,
            )
        )
    metrics: dict[str, list[float | None]] = {}
    for label in SLIDE_INCOME_LABELS:
        key = _slide_label_key(label)
        if not key:
            continue
        pat = re.escape(label) + r"\s+((?:\(?-?\d[\d,]*\.?\d*\)?\s*){" + str(n) + r"})"
        m = re.search(pat, text, re.I)
        if not m:
            continue
        nums = re.findall(r"\(?-?\d[\d,]*\.?\d*\)?", m.group(1))
        metrics[key] = [parse_number(x) for x in nums[:n]]
    if not metrics.get("rev"):
        return None
    rows: list[list[str]] = [["Line"] + [c.label for c in cols]]
    for label in SLIDE_INCOME_LABELS:
        key = _slide_label_key(label)
        series = metrics.get(key) if key else None
        if key == "total net sales":
            series = metrics.get("rev")
        if series:
            rows.append([label] + [str(v) if v is not None else "" for v in series])
    return ParsedTable(rows=rows, columns=cols, scale=1.0, currency="EUR")


def parse_slide_income_from_html(html_text: str, fy_end_month: int) -> list[ParsedTable]:
    tables: list[ParsedTable] = []
    seen_keys: set[tuple[str, ...]] = set()
    for block in extract_hidden_slide_blocks(html_text):
        parsed = parse_slide_income_block(block, fy_end_month)
        if not parsed:
            continue
        key = tuple(c.period_end for c in parsed.columns)
        if key in seen_keys:
            continue
        seen_keys.add(key)
        tables.append(parsed)
    tables.sort(key=lambda t: len(t.columns), reverse=True)
    return tables


def merge_slide_income_metrics(
    income_store: dict[PeriodKey, dict[str, Any]],
    slide_tables: list[ParsedTable],
    source: dict[str, str],
) -> None:
    """Merge GAAP slide income; overrides condensed press-release rows when fuller lines exist."""
    for table in slide_tables:
        raw = extract_metrics(table, INCOME_ALIASES)
        if raw.get("net_after_tax"):
            raw["net"] = raw["net_after_tax"]
        for j, (pk, col) in enumerate(period_keys_from_table(table)):
            entry = income_store.setdefault(pk, {"source": source, "fields": {}})
            entry["source"] = source
            entry["period_end"] = col.period_end
            for field, series in raw.items():
                if field == "net_after_tax" or j >= len(series):
                    continue
                val = series[j]
                if val is None:
                    continue
                if field == "cogs" and val < 0:
                    val = abs(val)
                if field in SLIDE_INCOME_FORCE_FIELDS or entry["fields"].get(field) is None:
                    entry["fields"][field] = val


def prior_ytd_period_end(period_end: str, ytd_months: int) -> tuple[str, int] | None:
    y, m, d = map(int, period_end.split("-"))
    if ytd_months == 6:
        return f"{y:04d}-03-31", 3
    if ytd_months == 9:
        return f"{y:04d}-06-30", 6
    if ytd_months == 12:
        return f"{y:04d}-09-30", 9
    return None


def derive_cf_from_ytd(
    ytd_store: dict[str, dict[int, dict[str, Any]]],
    cf_out: dict[PeriodKey, dict[str, Any]],
    fy_end: int,
) -> None:
    """Standalone quarterly CF = fiscal YTD − prior-quarter YTD (same as domestic XBRL path)."""
    cf_fields = ("op_cf", "inv_cf", "fin_cf", "net_chg", "capex")
    for pe, buckets in ytd_store.items():
        if 3 in buckets:
            pk = date_to_period_key(pe, fy_end)
            entry = cf_out.setdefault(pk, {"source": buckets[3]["source"], "fields": {}})
            for field in cf_fields:
                val = buckets[3]["fields"].get(field)
                if val is not None and entry["fields"].get(field) is None:
                    entry["fields"][field] = val
        for months, bucket in buckets.items():
            if months <= 3:
                continue
            prior = prior_ytd_period_end(pe, months)
            if not prior:
                continue
            prior_pe, prior_m = prior
            prior_bucket = ytd_store.get(prior_pe, {}).get(prior_m)
            if not prior_bucket:
                continue
            pk = date_to_period_key(pe, fy_end)
            entry = cf_out.setdefault(pk, {"source": bucket["source"], "fields": {}})
            for field in cf_fields:
                cur = bucket["fields"].get(field)
                prev = prior_bucket["fields"].get(field)
                if cur is not None and prev is not None and entry["fields"].get(field) is None:
                    entry["fields"][field] = round(cur - prev, 2)


def parse_cf_tables(
    tables: list[list[list[str]]],
    fy_end_month: int,
    cf_store: dict[PeriodKey, dict[str, Any]],
    ytd_store: dict[str, dict[int, dict[str, Any]]],
    source: dict[str, str],
) -> None:
    """Cash flow sections are often split across multiple HTML tables (e.g. TSM)."""
    needles = (
        "operating activities",
        "investing activities",
        "financing activities",
        "net increase in cash",
        "net change in cash",
    )
    for rows in tables:
        if table_score(rows, needles) <= 0:
            continue
        header_rows = rows[:12]
        cols = dedupe_columns(parse_columns(header_rows, "quarter", fy_end_month))
        if not cols:
            continue
        scale, _ = detect_scale_and_currency(rows)
        mini = ParsedTable(rows=rows, columns=cols, scale=scale)
        metrics = extract_metrics(mini, CF_ALIASES)
        for j, (pk, col) in enumerate(period_keys_from_table(mini)):
            if col.ytd_months > 3:
                bucket = ytd_store.setdefault(col.period_end, {}).setdefault(
                    col.ytd_months, {"source": source, "fields": {}}
                )
                for field, series in metrics.items():
                    if j < len(series) and series[j] is not None:
                        bucket["fields"].setdefault(field, series[j])
                continue
            for field, series in metrics.items():
                if j < len(series):
                    merge_metric(cf_store, pk, field, series[j], source)
                    if series[j] is not None:
                        ytd_store.setdefault(col.period_end, {}).setdefault(
                            3, {"source": source, "fields": {}}
                        )["fields"].setdefault(field, series[j])


def parse_tables_from_html(
    html_text: str,
    fy_end_month: int,
    income_store: dict[PeriodKey, dict[str, Any]],
    bs_store: dict[PeriodKey, dict[str, Any]],
    cf_store: dict[PeriodKey, dict[str, Any]],
    source: dict[str, str],
    ytd_cf_store: dict[str, dict[int, dict[str, Any]]] | None = None,
) -> str:
    """Extract income, BS, and CF from all tables in one HTML document. Returns currency."""
    currency = "USD"
    low_head = html_text[:8000].lower()
    for code in ("new taiwan", "taiwan dollar", "nt$", "ntd", "twd", "eur", "dkk", "gbp"):
        if code in low_head:
            currency = "TWD" if "taiwan" in code or code in ("nt$", "ntd", "twd") else code.upper()
            break
    if not html_has_financial_tables(html_text):
        slide_tables = parse_slide_income_from_html(html_text, fy_end_month)
        if slide_tables:
            if slide_tables[0].currency != "USD":
                currency = slide_tables[0].currency
            merge_slide_income_metrics(income_store, slide_tables, source)
        return currency
    tables = extract_tables(html_text)

    inc = find_best_table(
        tables,
        ("net sales", "net revenue", "total net sales", "gross profit", "operating profit", "net profit"),
        "quarter",
        fy_end_month,
    )
    if inc:
        if inc.currency != "USD":
            currency = inc.currency
        metrics = extract_metrics(inc, INCOME_ALIASES)
        for j, (pk, col) in enumerate(period_keys_from_table(inc)):
            for field, series in metrics.items():
                if j < len(series):
                    merge_metric(income_store, pk, field, series[j], source)
            cash_val = metrics.get("cash", [None] * len(inc.columns))
            if j < len(cash_val) and cash_val[j] is not None:
                entry = bs_store.setdefault(pk, {"source": source, "fields": {}, "period_end": col.period_end})
                entry["period_end"] = col.period_end
                merge_metric(bs_store, pk, "cash", cash_val[j], source)

    slide_tables = parse_slide_income_from_html(html_text, fy_end_month)
    if slide_tables:
        if slide_tables[0].currency != "USD":
            currency = slide_tables[0].currency
        merge_slide_income_metrics(income_store, slide_tables, source)

    bs = find_best_table(
        tables,
        ("total assets", "total liabilities", "total equity", "total current assets"),
        "instant",
        fy_end_month,
    )
    if bs:
        if bs.currency != "USD":
            currency = bs.currency
        metrics = extract_metrics(bs, BS_ALIASES)
        for j, (pk, col) in enumerate(period_keys_from_table(bs)):
            entry = bs_store.setdefault(pk, {"source": source, "fields": {}, "period_end": col.period_end})
            entry["period_end"] = col.period_end
            for field, series in metrics.items():
                if j < len(series):
                    merge_metric(bs_store, pk, field, series[j], source)

    ytd_cf = ytd_cf_store if ytd_cf_store is not None else {}
    parse_cf_tables(tables, fy_end_month, cf_store, ytd_cf, source)
    return currency


def collect_from_filing(
    cik: str,
    filing: dict[str, str],
    fy_end_month: int,
    index: dict[str, Any] | None = None,
) -> tuple[dict[PeriodKey, dict[str, Any]], dict[PeriodKey, dict[str, Any]], dict[PeriodKey, dict[str, Any]], str]:
    income_store: dict[PeriodKey, dict[str, Any]] = {}
    bs_store: dict[PeriodKey, dict[str, Any]] = {}
    cf_store: dict[PeriodKey, dict[str, Any]] = {}
    ytd_cf: dict[str, dict[int, dict[str, Any]]] = {}
    currency = "USD"

    idx = index or filing_index(cik, filing["accessionNumber"])
    docs = locate_financial_docs(idx, filing["primaryDocument"])
    source = {
        "form": filing["form"],
        "filingDate": filing["filingDate"],
        "accessionNumber": filing["accessionNumber"],
    }

    for doc in docs[:2]:
        url = filing_doc_url(cik, filing["accessionNumber"], doc)
        source = {**source, "url": url}
        try:
            html_text = sec_get_html(url)
        except OSError:
            continue
        cur = parse_tables_from_html(html_text, fy_end_month, income_store, bs_store, cf_store, source, ytd_cf)
        if cur:
            currency = cur

    return income_store, bs_store, cf_store, currency, ytd_cf


def filing_has_large_exhibit(cik: str, filing: dict[str, str]) -> int:
    """Rank filings by largest HTML exhibit size (prefer fsx / consolidated reports)."""
    idx = filing_index(cik, filing["accessionNumber"])
    ranked = _htm_candidates(idx, filing["primaryDocument"])
    max_size = ranked[0][1] if ranked else 0
    bonus = 0
    primary = filing["primaryDocument"].lower()
    if "fsx" in primary or "financial" in primary:
        bonus += 500_000
    if ranked and any(k in ranked[0][0].lower() for k in ("consolidated", "standalone", "financial")):
        bonus += 500_000
    return max_size + bonus


def collect_all(cik: str, n: int = 12) -> tuple[
    dict[PeriodKey, dict[str, Any]],
    dict[PeriodKey, dict[str, Any]],
    dict[PeriodKey, dict[str, Any]],
    str,
]:
    entity = load_entity(cik)
    fy_end = fiscal_year_end_month(entity)
    income: dict[PeriodKey, dict[str, Any]] = {}
    bs: dict[PeriodKey, dict[str, Any]] = {}
    cf: dict[PeriodKey, dict[str, Any]] = {}
    ytd_cf: dict[str, dict[int, dict[str, Any]]] = {}
    currency = "USD"

    filings = sorted(list_html_filings(cik, limit=15), key=lambda f: -filing_has_large_exhibit(cik, f))

    for filing in filings:
        idx = filing_index(cik, filing["accessionNumber"])
        i_s, b_s, c_s, cur, ytd_s = collect_from_filing(cik, filing, fy_end, index=idx)
        currency = cur or currency
        for pe, buckets in ytd_s.items():
            dst = ytd_cf.setdefault(pe, {})
            for months, bucket in buckets.items():
                db = dst.setdefault(months, {"source": bucket["source"], "fields": {}})
                for field, val in bucket["fields"].items():
                    if val is not None and db["fields"].get(field) is None:
                        db["fields"][field] = val
        for store, new in ((income, i_s), (bs, b_s), (cf, c_s)):
            for pk, entry in new.items():
                dst = store.setdefault(pk, {"source": entry["source"], "fields": {}})
                for field, val in entry["fields"].items():
                    if field == "period_end":
                        dst["period_end"] = val
                        continue
                    if dst["fields"].get(field) is None and val is not None:
                        dst["fields"][field] = val
        if len(income) >= n and len(bs) >= n and len(cf) >= n:
            break

    derive_cf_from_ytd(ytd_cf, cf, fy_end)

    return income, bs, cf, currency


def top_period_keys(store: dict[PeriodKey, dict[str, Any]], n: int) -> list[PeriodKey]:
    return sorted(store.keys(), reverse=True)[:n]


def build_quarter_meta(
    keys: list[PeriodKey],
    store: dict[PeriodKey, dict[str, Any]],
    fy_end: int,
) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for year, quarter in keys:
        entry = store[(year, quarter)]
        pe = entry.get("period_end") or period_end_for_quarter(year, quarter)
        out.append(
            {
                "label": quarter_label(pe),
                "periodEnd": pe,
                "fiscalLabel": fiscal_quarter_label(pe, fy_end),
                "source": entry["source"],
            }
        )
    return out


def series_from_store(store: dict[PeriodKey, dict[str, Any]], keys: list[PeriodKey], field: str) -> list[float | None]:
    return [store[k]["fields"].get(field) for k in keys]


def build_income_rows_from_store(store: dict[PeriodKey, dict[str, Any]], keys: list[PeriodKey]) -> list[dict[str, Any]]:
    n = len(keys)
    rev = series_from_store(store, keys, "rev")
    gross = series_from_store(store, keys, "gross")
    gm = series_from_store(store, keys, "gm_pct")
    net = series_from_store(store, keys, "net")
    eps_b = series_from_store(store, keys, "eps_b")
    op = series_from_store(store, keys, "op")
    cogs_raw = series_from_store(store, keys, "cogs")
    pretax = series_from_store(store, keys, "pretax")
    tax = series_from_store(store, keys, "tax")

    cogs: list[float | None] = []
    cogs_derived: list[bool] = []
    for i in range(n):
        if cogs_raw[i] is not None:
            cogs.append(cogs_raw[i])
            cogs_derived.append(False)
        elif rev[i] is not None and gross[i] is not None:
            cogs.append(rev[i] - gross[i])
            cogs_derived.append(True)
        else:
            cogs.append(None)
            cogs_derived.append(False)

    for i in range(n):
        if gm[i] is None and rev[i] not in (None, 0) and gross[i] is not None:
            gm[i] = round(gross[i] / rev[i] * 100, 1)

    yoy: list[float | None] = []
    for i, r in enumerate(rev):
        j = i + 4
        if r is None or j >= n or rev[j] is None or rev[j] == 0:
            yoy.append(None)
        else:
            yoy.append((r - rev[j]) / abs(rev[j]) * 100)

    metrics: dict[str, list[float | None]] = {
        "Total Revenues": rev,
        "Total Revenues %Chg": yoy,
        "Cost of Sales": cogs,
        "Gross Profit": gross,
        "Gross Profit Margin": gm,
        "Operating Profit": op,
        "Income Before Provision for Income Taxes": pretax,
        "Provision for Income Taxes": tax,
        "Consolidated Net Income": net,
        "Basic EPS": eps_b,
    }

    optional = {
        "Operating Profit",
        "Income Before Provision for Income Taxes",
        "Provision for Income Taxes",
        "Cost of Sales",
        "Gross Profit",
        "Gross Profit Margin",
        "Basic EPS",
    }
    rows_out: list[dict[str, Any]] = []
    for spec in INCOME_ROWS:
        series = metrics.get(spec.label)
        if series is None:
            continue
        if spec.label in optional and all(v is None for v in series):
            continue
        if spec.unit == "$":
            dflags = {"Cost of Sales": cogs_derived, "Gross Profit": cogs_derived}
            dflags_row = dflags.get(spec.label, [False] * n)
            values = [fmt_dollar(v, derived=dflags_row[i]) if v is not None else "—" for i, v in enumerate(series)]
        elif spec.unit == "%":
            values = [fmt_pct(v) if spec.label.endswith("%Chg") else fmt_margin(v) for v in series]
        elif spec.unit == "eps":
            values = [fmt_eps(v) if v is not None else "—" for v in series]
        else:
            values = [str(v) if v is not None else "—" for v in series]
        rows_out.append(row_from_spec(spec, values))
    return rows_out


def build_bs_rows_from_store(store: dict[PeriodKey, dict[str, Any]], keys: list[PeriodKey]) -> list[dict[str, Any]]:
    n = len(keys)
    cash = series_from_store(store, keys, "cash")
    assets = series_from_store(store, keys, "assets")
    current_assets = series_from_store(store, keys, "current_assets")
    noncurrent_assets = series_from_store(store, keys, "noncurrent_assets")
    liab = series_from_store(store, keys, "liab")
    equity = series_from_store(store, keys, "equity")

    for i in range(n):
        if assets[i] is None and current_assets[i] is not None and noncurrent_assets[i] is not None:
            assets[i] = current_assets[i] + noncurrent_assets[i]
        if assets[i] is None and liab[i] is not None and equity[i] is not None:
            assets[i] = liab[i] + equity[i]

    metrics: dict[str, list[float | None]] = {
        "Total Cash and Cash Equivalents": cash,
        "Total Assets": assets,
        "Total Liabilities": liab,
        "Total Shareholders' Equity": equity,
    }

    rows_out: list[dict[str, Any]] = []
    for spec in BALANCE_SHEET_ROWS:
        if spec.section:
            rows_out.append(section_divider_row(spec, n))
            continue
        series = metrics.get(spec.label)
        if series is None:
            continue
        if all(v is None for v in series):
            continue
        derived = spec.label == "Total Cash and Cash Equivalents" and any(v is not None for v in series)
        values = [fmt_dollar(v, derived=derived) if v is not None else "—" for v in series]
        rows_out.append(row_from_spec(spec, values))
    return rows_out


def build_cf_rows_from_store(store: dict[PeriodKey, dict[str, Any]], keys: list[PeriodKey]) -> list[dict[str, Any]]:
    n = len(keys)
    op_cf = series_from_store(store, keys, "op_cf")
    inv_cf = series_from_store(store, keys, "inv_cf")
    fin_cf = series_from_store(store, keys, "fin_cf")
    net_chg = series_from_store(store, keys, "net_chg")
    capex = series_from_store(store, keys, "capex")

    for i in range(n):
        if net_chg[i] is None and op_cf[i] is not None and inv_cf[i] is not None and fin_cf[i] is not None:
            net_chg[i] = op_cf[i] + inv_cf[i] + fin_cf[i]

    fcf = [
        (op_cf[i] + capex[i]) if op_cf[i] is not None and capex[i] is not None else None
        for i in range(n)
    ]

    metrics: dict[str, list[float | None]] = {
        "Cash from Operating Activities": op_cf,
        "Cash from Investing Activities": inv_cf,
        "Cash from Financing Activities": fin_cf,
        "Net Change in Cash": net_chg,
        "Capital Expenditure": capex,
        "Free Cash Flow": fcf,
    }

    rows_out: list[dict[str, Any]] = []
    for spec in CASH_FLOW_ROWS:
        if spec.section:
            rows_out.append(section_divider_row(spec, n))
            continue
        series = metrics.get(spec.label)
        if series is None:
            continue
        if all(v is None for v in series):
            continue
        values = [fmt_dollar(v, derived=spec.derived) if v is not None else "—" for v in series]
        rows_out.append(row_from_spec(spec, values))
    return rows_out


def _edgar_block(cik: str, latest: dict[str, str]) -> dict[str, Any]:
    return {
        "cik": cik.zfill(10),
        "latestQuarterlyFilingDate": latest["filingDate"],
        "latestQuarterlyForm": latest["form"],
        "latestQuarterlyAccession": latest["accessionNumber"],
        "latestQuarterlyUrl": latest["url"],
        "filerType": "fpi",
    }


def build_all_html_documents(ticker: str) -> dict[str, dict[str, Any]]:
    """Build income, balance-sheet, and cash-flow from 6-K HTML in one SEC pass."""
    from sec_financials import missing_data_columns

    t = ticker.strip().upper()
    cik = lookup_cik(t)
    entity = load_entity(cik)
    company = entity.get("name") or t
    fy_end = fiscal_year_end_month(entity)
    income_store, bs_store, cf_store, currency = collect_all(cik, 12)
    if currency == "USD" and "taiwan" in company.lower():
        currency = "TWD"
    latest = latest_quarterly_filings(cik, limit=1)[0]
    out: dict[str, dict[str, Any]] = {}

    if len(income_store) >= 12:
        keys = top_period_keys(income_store, 12)
        quarters = build_quarter_meta(keys, income_store, fy_end)
        rows = build_income_rows_from_store(income_store, keys)
        doc = {
            "schemaVersion": 1,
            "statementType": "income",
            "ticker": t,
            "companyName": company,
            "currency": currency,
            "unit": "millions",
            "fiscalYearEndMonth": fy_end,
            "edgar": _edgar_block(cik, latest),
            "quarters": quarters,
            "rows": rows,
            "summary": {
                "subtitle": (
                    f"{company} · Last 12 quarters · {currency} millions. "
                    "Source: SEC 6-K HTML financial tables."
                ),
                "fiscalMapping": " · ".join(f"{q['label']} = {q['fiscalLabel']}" for q in quarters),
                "stats": [],
                "defaultChartRows": ["Total Revenues", "Consolidated Net Income"],
            },
            "notes": [
                "Foreign private issuer: quarterly data parsed from SEC 6-K HTML tables.",
                "Cost of Sales* derived when Gross Profit and Revenue are available but COGS is not reported.",
            ],
            "verification": verify_income_rows(rows, len(quarters)),
        }
        if not missing_data_columns(doc):
            out["income"] = doc

    if len(bs_store) >= 12:
        keys = top_period_keys(bs_store, 12)
        quarters = build_quarter_meta(keys, bs_store, fy_end)
        rows = build_bs_rows_from_store(bs_store, keys)
        doc = {
            "schemaVersion": 1,
            "statementType": "balance-sheet",
            "ticker": t,
            "companyName": company,
            "currency": currency,
            "unit": "millions",
            "fiscalYearEndMonth": fy_end,
            "edgar": _edgar_block(cik, latest),
            "quarters": quarters,
            "rows": rows,
            "summary": {
                "subtitle": (
                    f"{company} · Last 12 quarters · {currency} millions · Period-end. "
                    "Source: SEC 6-K HTML (FPI/ADR)."
                ),
                "fiscalMapping": " · ".join(f"{q['label']} = {q['fiscalLabel']}" for q in quarters),
                "stats": [],
                "defaultChartRows": ["Total Assets", "Total Shareholders' Equity"],
            },
            "notes": ["Balance sheet from SEC 6-K HTML instant/period-end columns."],
            "verification": verify_bs_rows(rows, len(quarters)),
        }
        if not missing_data_columns(doc):
            out["balance-sheet"] = doc

    if len(cf_store) >= 12:
        keys = top_period_keys(cf_store, 12)
        quarters = build_quarter_meta(keys, cf_store, fy_end)
        rows = build_cf_rows_from_store(cf_store, keys)
        doc = {
            "schemaVersion": 1,
            "statementType": "cash-flow",
            "ticker": t,
            "companyName": company,
            "currency": currency,
            "unit": "millions",
            "fiscalYearEndMonth": fy_end,
            "edgar": _edgar_block(cik, latest),
            "quarters": quarters,
            "rows": rows,
            "summary": {
                "subtitle": (
                    f"{company} · Last 12 quarters · {currency} millions · Three months ended. "
                    "Source: SEC 6-K HTML (FPI/ADR)."
                ),
                "fiscalMapping": " · ".join(f"{q['label']} = {q['fiscalLabel']}" for q in quarters),
                "stats": [],
                "defaultChartRows": ["Cash from Operating Activities", "Free Cash Flow"],
            },
            "notes": [
                "Cash flow from SEC 6-K HTML tables.",
                "Net Change in Cash* derived as Operating + Investing + Financing when not reported.",
            ],
            "verification": verify_cf_rows(rows, len(quarters)),
        }
        if not missing_data_columns(doc):
            out["cash-flow"] = doc

    if "income" not in out:
        raise SystemExit(f"Only found {len(income_store)} income quarters in 6-K HTML (need 12 with anchors)")
    return out


def write_all_html_json(ticker: str) -> dict[str, Any]:
    docs = build_all_html_documents(ticker)
    paths = {}
    for stmt, doc in docs.items():
        path = json_path(ticker, stmt)
        save_json(path, doc)
        paths[stmt] = path
    return paths


# Back-compat aliases
build_all_fpi_documents = build_all_html_documents
write_all_fpi_json = write_all_html_json


def build_fpi_income_document(ticker: str) -> dict[str, Any]:
    return build_all_html_documents(ticker)["income"]


def build_fpi_bs_document(ticker: str) -> dict[str, Any]:
    doc = build_all_html_documents(ticker).get("balance-sheet")
    if not doc:
        raise SystemExit("Insufficient balance-sheet anchor data in 6-K HTML filings")
    return doc


def build_fpi_cf_document(ticker: str) -> dict[str, Any]:
    doc = build_all_html_documents(ticker).get("cash-flow")
    if not doc:
        raise SystemExit("Insufficient cash-flow anchor data in 6-K HTML filings")
    return doc


def write_fpi_income_json(ticker: str):
    path = json_path(ticker, "income")
    save_json(path, build_all_html_documents(ticker)["income"])
    return path


def write_fpi_bs_json(ticker: str):
    doc = build_all_html_documents(ticker).get("balance-sheet")
    if not doc:
        raise SystemExit("Insufficient balance-sheet anchor data in 6-K HTML filings")
    path = json_path(ticker, "balance-sheet")
    save_json(path, doc)
    return path


def write_fpi_cf_json(ticker: str):
    doc = build_all_html_documents(ticker).get("cash-flow")
    if not doc:
        raise SystemExit("Insufficient cash-flow anchor data in 6-K HTML filings")
    path = json_path(ticker, "cash-flow")
    save_json(path, doc)
    return path
